name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Jekyll site
      run: |
        sudo gem install jekyll bundler
        sudo bundle install
        bundle exec jekyll build

    - name: Install putty-tools
      run: sudo apt-get update && sudo apt-get install -y putty-tools

    - name: Echo
      run: |
        pwd
        echo Wurst
        ls -a

    - name: lftp-mirror-action
      uses: pressidium/lftp-mirror-action@v1
      with:
          # SFTP credentials
          host: ${{ secrets.ftp_url }}
          port: ${{ secrets.ftp_port }}
          user: ${{ secrets.ftp_user }}
          pass: ${{ secrets.ftp_password }}
          # lftp settings
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: '_site'
          remoteDir: '.'
          reverse: true
          ignoreFile: '.lftp_ignore'
          options: '--verbose'
