name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Jekyll site
      run: |
        sudo gem install jekyll bundler
        sudo bundle install
        bundle exec jekyll build

    - name: Install putty-tools
      run: sudo apt-get update && sudo apt-get install -y putty-tools

    - name: Echo
      run: |
        pwd
        echo Wurst
        ls -a

    - name: Deploy via SFTP
      uses: Luis97lol/PSFTP@v1.4
      with:
        host: ${{ secrets.ftp_url }}
        user: ${{ secrets.ftp_user }}
        pass: ${{ secrets.ftp_password }}
        scriptPath: deploy.sh

